# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 146b1d63a3cf1a5937b744b8756427878274ad212364b5c9d1c41c68f284cb5c7165a2491f3e6c4606822d3566877df2b88a2e93b0f83c6edd9284d215c00c99

test:
  secret_key_base: 3a09f64fb3b8a1ff2c5b971b0022b6ada9844ef25561c9b1e3afa29c05d1a7861f09685bd2d33f89c8808a3eb72faa7a7e5846c5a417c078aecf4085f74d63e8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
